- hosts: "current"
  vars_files: 
    - ./vars/commons.yml
    - "./vars/{{ ansible_facts['os_family'] }}.yml"

  tasks:
    - name: Common Before
      include_tasks: ./tasks/before.yml

    - name: MacOS
      include_tasks: ./tasks/darwin.yml
      when: ansible_facts['os_family'] == "Darwin"

    - name: Ubuntu
      include_tasks: ./tasks/ubuntu.yml
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Common After
      include_tasks: ./tasks/after.yml

  handlers:
    - name: Restart ActivityMonitor
      command: killall "Activity Monitor"
      ignore_errors: yes

    - name: Restart AppStore
      command: killall "App Store"
      ignore_errors: yes

    - name: Restart MenuBar
      command: killall SystemUIServer
      ignore_errors: yes

    - name: Restart Dock
      command: killall Dock
      ignore_errors: yes

    - name: Restart Finder
      command: killall Finder
      ignore_errors: yes

    - name: Restart Safari
      command: killall Safari
      ignore_errors: yes

    - name: Restart Spotlight
      command: killall mds
      ignore_errors: yes
      become: yes

    - name: Restart LaunchServices
      command: killall launchservicesd
      ignore_errors: yes
      become: yes
