- hosts: "current"
  vars_files: 
    - ./vars/commons.yml
    - "./vars/{{ ansible_facts['os_family'] }}.yml"

  tasks:
    - name: Common Before
      include_tasks: ./tasks/before.yml

    - name: MacOS
      include_tasks: ./tasks/darwin.yml
      when: ansible_facts['os_family'] == "Darwin"

    - name: Ubuntu
      include_tasks: ./tasks/ubuntu.yml
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Common After
      include_tasks: ./tasks/after.yml
