  - name: "Ensure Git Repository Updated"
    git:
      repo: "{{ repository }}"
      dest: "{{ home }}/.config"
      accept_hostkey: true
    tags: 
      -  auth

  - name: "Add GitHub token"
    shell: "echo \"{{lookup('unvault', '{{ config_dir }}/personal/github_general_personal_token')}}\"|gh auth login --with-token "
    tags: 
      - auth
      - never
