  - name: Homebrew
    include_tasks: darwin/homebrew.yml
    no_log: true

  - name: System Configuration
    include_tasks: darwin/configuration.yml


  - name: Change Shortcuts
    command: >
      defaults write com.apple.symbolichotkeys.plist AppleSymbolicHotKeys -dict-add {{ item.key }} '
        <dict>
          <key>enabled</key><{{ item.enabled }}/>
          <key>value</key><dict>
            <key>type</key><string>standard</string>
            <key>parameters</key>
            <array>
              <integer>{{ item.parameters.0 }}</integer>
              <integer>{{ item.parameters.1 }}</integer>
              <integer>{{ item.parameters.2 }}</integer>
            </array>
          </dict>
        </dict>'
    loop: "{{ enabled_shortcuts }}"

  - name: Disable Shortcuts
    command: >
      defaults write com.apple.symbolichotkeys.plist AppleSymbolicHotKeys -dict-add {{ item.key }} '
        <dict>
          <key>enabled</key><{{ item.enabled }}/>
        </dict>'
    loop: "{{ disabled_shortcuts }}"

  - name: Restart Dock
    command: killall Dock

  # Install Nerd Fonts
  - name: Ensure fonts directory
    file:
      path: "{{ home }}/Library/Fonts/NerdFonts"
      state: directory

  - name: Check Hack exists
    shell: "ls {{ home }}/Library/Fonts/NerdFonts/Hack*Nerd*Font*Complete*"
    register: hack_exists
    ignore_errors: true

  - name: Ensure Nerd Font Installed
    shell: |
      git clone --filter=blob:none --sparse git@github.com:ryanoasis/nerd-fonts {{ download_dir }}/nerd-fonts
      cd {{ download_dir }}/nerd-fonts
      git sparse-checkout add patched-fonts/Hack
      ./install.sh hack
    when: hack_exists is failed

