############ Core Install #############
- name: Core Installation
  tags: 
    - core
    - basic
    - extended
  block:
    - name: Ensure Core Taps Sourced
      homebrew_tap:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default('present') }}"
      loop: "{{ core_taps }}"

    - name: Ensure Core Packages Installed
      homebrew:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default('present') }}"
      loop: "{{ core_packages }}"

    - name: Ensure Core Casks Installed
      homebrew_cask:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default('present') }}"
      loop: "{{ core_apps }}"

    - name: Ensure node 18 installed
      shell:
        cmd: |
          source /opt/homebrew/opt/nvm/nvm.sh
          nvm install 18
          nvm use 18
        creates: "{{ home }}/.nvm/versions/node"
        executable: /bin/bash
      register: test

    - name: Download LunarVim Installation
      get_url:
        url: https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh
        dest: "{{ download_dir }}/lvim_install.sh"
        checksum: sha256:297a628c7a806dc5c9088364b69d633254a7bc413ff594a6b25d0e2659aad35b
        mode: 0755

    - name: Ensure LunarVim Installed
      shell:
        cmd: >
          LV_BRANCH='release-1.3/neovim-0.9' 
          yes | {{ download_dir }}/lvim_install.sh && rm -rf {{ config_dir }}/lvim
        creates: "{{ home }}/.local/bin/lvim"

    - name: Ensure Chezmoi Initialized
      command: "chezmoi init {{ github_username }}"
      args:
        creates: "~/.local/share/chezmoi"

- name: Ensure core Chezmoi Applied
  tags: ["core", "never"]
  command: "chezmoi -R --force apply {{ config_dir }}/lvim {{ config_dir }}/tmux"
  args:
    creates: "{{ config_dir }}/lvim"

#######################################
######## System Config Install ########

- name: System Config Installation
  tags: 
    - system_config
    - basic
  block:
  - name: Ensure System Config Packages Installed
    homebrew:
      name: "{{ item.name | default(item) }}"
      state: "{{ item.state | default('present') }}"
    loop: "{{ system_config_packages }}"

  - name: Ensure System Config Apps Installed
    homebrew_cask:
      name: "{{ item.name | default(item) }}"
      state: "{{ item.state | default('present') }}"
    loop: "{{ system_config_apps }}"

#######################################
############ Auth Install #############

- name: Ensure Auth Packages Installed
  homebrew:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ auth_packages }}"
  tags: auth

#######################################
############ Basic Install #############

- name: Basic Installation
  tags: 
    - basic
    - extended
  block:
  - name: Ensure Base Packages Installed
    homebrew:
      name: "{{ item.name | default(item) }}"
      state: "{{ item.state | default('present') }}"
    when: 
    loop: "{{ base_packages }}"
  - name: Ensure Base Apps Installed
    homebrew_cask:
      name: "{{ item.name | default(item) }}"
      state: "{{ item.state | default('present') }}"
    loop: "{{ base_apps }}"

#######################################
############ Dev Install #############

- name: Ensure Dev Apps Installed
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ dev_apps }}"
  tags: 
    - dev
    - extended

#######################################
######## Extended Install ########

- name: Extended Installation
  tags: extended
  block:
  - name: Ensure Extended Taps Sourced
    homebrew_tap:
      name: "{{ item.name | default(item) }}"
      state: "{{ item.state | default('present') }}"
    loop: "{{ extended_taps }}"
  - name: Ensure Extended Packages Installed
    homebrew:
      name: "{{ item.name | default(item) }}"
      state: "{{ item.state | default('present') }}"
    loop: "{{ extended_packages }}"
  - name: Ensure Extended Apps Installed
    homebrew_cask:
      name: "{{ item.name | default(item) }}"
      state: "{{ item.state | default('present') }}"
    loop: "{{ extended_apps }}"
