- name: Add Hombrew Taps
  homebrew_tap:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ homebrew_taps }}"

- name: Ensure Homebrew Packages Installed
  homebrew:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ homebrew_installed_packages }}"

- name: Ensure Homebrew Casks Installed
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ homebrew_cask_apps }}"

- name: Ensure node 18 installed
  shell:
    cmd: |
      source /opt/homebrew/opt/nvm/nvm.sh
      nvm install 18
      nvm use 18
    creates: "{{ home }}/.nvm/versions/node"
    executable: /bin/bash
  register: test

- name: Download LunarVim Installation
  get_url:
    url: https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh
    dest: "{{ download_dir }}/lvim_install.sh"
    checksum: sha256:297a628c7a806dc5c9088364b69d633254a7bc413ff594a6b25d0e2659aad35b
    mode: 0755

- name: Ensure LunarVim Installed
  shell:
    cmd: >
      LV_BRANCH='release-1.3/neovim-0.9' 
      yes | {{ download_dir }}/lvim_install.sh
    creates: "{{ home }}/.local/bin/lvim"

